services:
  - type: web
    name: vip-boti
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NVIDIA_NIM_API_KEY
        fromEnv: NVIDIA_API_KEY
      - key: WHATSAPP_ACCESS_TOKEN
        fromEnv: META_TOKEN
      - key: WHATSAPP_PHONE_NUMBER_ID
        fromEnv: META_PHONE_ID
      - key: WHATSAPP_VERIFY_TOKEN
        fromEnv: VERIFY_TOKEN
      - key: MONGO_URI
        fromEnv: MONGODB_URI
      - key: MONGO_DB_NAME
        value: vip_numbers_bot
      - key: ADMIN_PHONE
        value: "212778375026"
